name: Custom Test Workflow

on:  
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 17  # Change Java version if needed
      MAVEN_COMMAND: "mvn test"  # Change Maven command if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Tests
        run: ${{ env.MAVEN_COMMAND }}
