name: Smoke Test to Validate Application Health and Basic Functionality

on:
  workflow_dispatch:  # Triggered manually via GitHub UI

jobs:
  set-env:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      MAVEN_COMMAND: mvn test -P qa -P smoke -P chrome

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '${{ env.JAVA_VERSION }}'

      - name: Install Chrome
        run: |
          sudo apt-get update  # Updates the package list
          sudo apt-get install -y google-chrome-stable  # Installs the stable version of Google Chrome

      - name: Install Xvfb (Virtual Display)
        run: |
          sudo apt-get install -y xvfb  # Install Xvfb package
          Xvfb :99 -screen 0 1920x1080x24 &  # Starts Xvfb on display 99 (sets up a virtual display)

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Verify ChromeDriver Installation
        run: chromedriver --version

      - name: Run Tests
        run: |
          export DISPLAY=:99  # Sets the display variable to use the Xvfb display
          ${{ env.MAVEN_COMMAND }}  # Runs the Maven command defined in 'env'
        working-directory: Selenium
