name: Run Tests Manually to select the options

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment (qa/preprod/prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - preprod
          - prod
      browser:
        description: 'Select Browser (chrome/firefox/edge)'
        required: true
        default: 'firefox'
        type: choice
        options:
          - chrome
          - firefox
          - edge
      test_type:
        description: 'Type of Testing (smoke/regression)'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Xvfb (Virtual Display)  # Install Xvfb to simulate a display (needed for non-headless mode)
        run: |
          sudo apt-get install -y xvfb  # Install Xvfb package
          Xvfb :99 -screen 0 1920x1080x24 &  # Starts Xvfb on display 99 (sets up a virtual display)
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven tests
        run: mvn test -P ${{ github.event.inputs.environment }} -P ${{ github.event.inputs.test_type }} -P ${{ github.event.inputs.browser }}
        working-directory: Selenium  # Specifies the working directory for Maven to run the command
